""" Defines initial migration for user app """
# Generated by Django 2.2.12 on 2022-02-18 21:08
from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):
    """ Offical Django syntax definition for user models """
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128,
                 verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True,
                 verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True,
                 verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True,
                 verbose_name='date joined')),
                ('profile_pic', models.ImageField(blank=True,
                 default=user.utils.get_default_profile_pic, max_length=200,
                 upload_to=user.utils.get_profile_pic)),
                ('hide_email', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
