# Generated by Django 2.2.12 on 2022-02-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_pic.png', max_length=200,
                                    upload_to='profile_images'),
        ),
    ]
